# Generated by Django 5.0.7 on 2024-07-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_myprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='serviceimages/')),
            ],
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='image',
            field=models.ImageField(upload_to='profileimages/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projectimages/'),
        ),
    ]
