# Generated by Django 5.0.7 on 2024-07-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_services_alter_myprofile_image_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
